version: '3.6'
services:
  wilayah_db:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=wilayah_db
      - POSTGRES_USER=wilayah_db
      - POSTGRES_DB=wilayah_db
    volumes:
      - wilayah_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  wilayah_data: